version: '3'
services:
        pfsense_scan:
                container_name: pfsense_scan
                build: .
                ports:
                        - "8082:80"
                restart: always

